name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
      
      - name: Build client application
        run: npm run build:client

      - name: Deploy files to the server
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avzr --delete
          path: dist/static/*
          remote_path: /var/www/html/
          remote_host: ${{ secrets.VDS_SELECTEL_HOST }}
          remote_user: ${{ secrets.VDS_SELECTEL_USERNAME }}
          remote_key: ${{ secrets.VDS_SELECTEL_KEY }}
